#!/bin/bash
set -e
find_list=$(find . -not -path '*/\.*' -type f $(printf "! -name %s " $(cat .gitignore)))
without_eol=$(file $find_list | grep 'no line terminators') || true
echo $without_eol
if [[ ! -z $without_eol ]]; then
    false 
fi
python3 -m flake8 -j auto
docs/coverage.py
